easy_admin:
    site_name: App Builders Admin
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
        - App\Entity\UserDetails
        - App\Entity\Project
        - App\Entity\Quote
